# Generated by Django 3.1.1 on 2020-09-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
