# Generated by Django 3.1.1 on 2020-10-05 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='replytimestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
